dist: xenial
branches:
  only:
    - master
language: csharp
solution: ServiceItemsPlanningPlugin.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build ServiceItemsPlanningPlugin.sln
  - dotnet test -v n ServiceItemsPlanningPlugin.Integration.Test/ServiceItemsPlanningPlugin.Integration.Test.csproj
